cmake_minimum_required(VERSION 3.16)
project(priority_thread_pool LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
find_package(Threads REQUIRED)
add_executable(ptp_test test.cpp)
target_link_libraries(ptp_test PRIVATE Threads::Threads)
add_executable(ptp_example example.cpp)
target_link_libraries(ptp_example PRIVATE Threads::Threads)
enable_testing()
add_test(NAME priority_thread_pool COMMAND ptp_test)
set_tests_properties(priority_thread_pool PROPERTIES TIMEOUT 15)
